export const LATENCY=0;
export const LOCATIONS=["Bharatpur","Ratnanagar","Khairahani","Rapti","Kalika","Madi","Ichchhakamana"];
export const CIVIC_LEVELS=[{min:0,label:"Getting Started"},{min:200,label:"Active Reporter"},{min:400,label:"Community Builder"},{min:600,label:"Great Community Contributor"},{min:800,label:"Civic Champion"}];
export function levelForScore(score){return[...CIVIC_LEVELS].reverse().find(level=>score>=level.min)||CIVIC_LEVELS[0];}
async function api(path,options={}){const response=await fetch(`/api${path}`,{credentials:"include",...options,headers:{"Content-Type":"application/json","X-CivicAI-CSRF":"1",...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||"Could not load CivicAI data.");return body.data;}
async function mine(){return api("/reports/my?limit=50");}
async function community(){return api("/reports/community?limit=5");}
function severity(priority){return priority>=85?"critical":priority>=70?"high":priority>=45?"medium":"low";}
function timeline(report){const steps=["submitted","under_review","verified","assigned","in_progress","resolved","closed"];const at=steps.indexOf(report.status);return steps.slice(0,6).map((key,i)=>({key,label:key.replaceAll("_"," "),done:i<=at,current:i===at,at:i===0?report.submittedAt:null}));}
export async function fetchCivicScore(){const data=await mine();const count=data.stats.total,score=Math.min(1000,count*25),level=levelForScore(score),next=CIVIC_LEVELS.find(x=>x.min>score);return{score,max:1000,level:level.label,nextLevel:next?.label||"Civic Champion",pointsToNext:next?next.min-score:0,percentile:0,breakdown:[{key:"reports",label:"Reports",value:String(count),hint:"Filed reports",tone:"primary"},{key:"helpful",label:"Pending",value:String(data.stats.pending),hint:"Awaiting action",tone:"brand"},{key:"confirmed",label:"Resolved",value:String(data.stats.resolved),hint:"Resolved issues",tone:"success"},{key:"impact",label:"Impact",value:`+${score}`,hint:"Civic points",tone:"ai"}]};}
export async function fetchNearbyIssues(){const data=await community();return data.items.map(r=>({...r,severity:severity(r.priority||0),distance:"Community",location:r.location||r.address||"Your community",votes:r.confirmed||0,mapX:50,mapY:50,communityVerification:{votes:{},myVote:r.myVote},legitimacy:{total:(r.confirmed||0)+(r.rejected||0),legit:r.confirmed||0,fake:r.rejected||0,label:r.legitimacyPercent==null?"Not verified":`${r.legitimacyPercent}% verified`,score:r.legitimacyPercent||0}}));}
export async function fetchRecentReports(){const data=await mine();return{items:data.items.slice(0,3).map(r=>({...r,severity:severity(r.priority||0),eta:"Updated from CivicAI",timeline:timeline(r)}))};}
export async function fetchCommunityImpact(){const data=await mine();return{stats:[{label:"Issues resolved",value:String(data.stats.resolved),tone:"success"},{label:"Total reports",value:String(data.stats.total),tone:"primary"},{label:"In progress",value:String(data.stats.inProgress),tone:"brand"},{label:"Critical",value:String(data.stats.critical),tone:"ai"}],chart:[],note:"These totals come from your CivicAI report records."};}
export async function fetchCivicInsight(){const data=await mine();return{badge:"Live Insight",headline:`${data.stats.pending} reports are awaiting action`,body:`You have ${data.stats.inProgress} reports in progress and ${data.stats.resolved} resolved.`,points:[],confidence:"Database derived"};}
export async function fetchNotifications(){const data=await api("/notifications");return {...data,items:(data.items||[]).map((item)=>({...item,iconKey:item.kind==="status"?"progress":item.kind==="resolved"?"resolved":"digest",time:item.createdAt?new Date(item.createdAt).toLocaleString():""}))};}
export async function markNotificationsRead({all=false,ids=[]}={}){return api("/notifications/read",{method:"POST",body:JSON.stringify({all,ids}),csrf:true});}
