import express from "express";
import multer from "multer";
import path from "node:path";
import { createHash, randomBytes, randomUUID } from "node:crypto";
import { sql } from "./db.js";
import { requireAuth } from "./auth.js";
import { createRateLimiter } from "./security.js";
import { CATEGORIES, getCategory } from "./analysis.js";
import { analyzeReportWithAI } from "./ai/service.js";
import { removeEvidence, storeEvidence, uploadDir, validateEvidence } from "./evidence-storage.js";
import { CATEGORY_KEYS, cleanText, STATUS_TRANSITIONS, validateReportInput } from "./report-validation.js";

export const reportsRouter=express.Router();
const upload=multer({storage:multer.memoryStorage(),limits:{files:6,fileSize:8*1024*1024,fields:20,fieldSize:32*1024}});
const createLimiter=createRateLimiter({windowMs:60*60*1000,limit:Number(process.env.REPORT_RATE_LIMIT||10),key:(req)=>`${req.ip}:${req.user?.id||"anon"}`});
const guestCreateLimiter=createRateLimiter({windowMs:60*60*1000,limit:Number(process.env.GUEST_REPORT_RATE_LIMIT||5),key:(req)=>`guest:${req.ip}`});
const guestTrackLimiter=createRateLimiter({windowMs:15*60*1000,limit:30,key:(req)=>`guest-track:${req.ip}`});
const PUBLIC_REPORT_STATUSES=new Set(["submitted","under_review","verified","assigned","in_progress","resolved","closed"]);
const DEPARTMENTS=new Set(CATEGORIES.map((category)=>category.department));
const GUEST_REPORTER="guest";
const GUEST_ACCESS_TTL_MS=30*86400000;

function fail(res,status,code,message,details){return res.status(status).json({success:false,error:{code,message,...(details?{details}:{})}});}
function ok(res,data,status=200,meta){return res.status(status).json({success:true,data,...(meta?{meta}:{})});}
function hashGuestToken(token){return createHash("sha256").update(token).digest("hex");}
function guestToken(){return randomBytes(32).toString("base64url");}
function reportId(){for(let i=0;i<5;i++){const id=`CIV-${new Date().getUTCFullYear()}-${randomBytes(4).readUInt32BE()%1000000}`;if(!sql.prepare("SELECT 1 FROM reports WHERE id=?").get(id))return id;}return `CIV-${new Date().getUTCFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;}
function canView(user,row){return user?.role==="admin"||(user?.role==="citizen"&&row.citizen_id===user.id)||(user?.role==="authority"&&(row.department===user.department||row.assigned_authority_id===user.id));}
function canViewEvidence(user,row){return canView(user,row);}
function canManage(user,row){return user?.role==="admin"||(user?.role==="authority"&&(row.department===user.department||row.assigned_authority_id===user.id));}
function isPublicReport(row){return Boolean(row&&row.citizen_id&&PUBLIC_REPORT_STATUSES.has(row.status));}
function addNotification(userId,reportId,kind,title,body,now=new Date().toISOString()){sql.prepare("INSERT INTO notifications (id,user_id,report_id,kind,title,body,read_at,created_at) VALUES (?,?,?,?,?,?,NULL,?)").run(`not_${randomUUID()}`,userId,reportId,kind,title,body,now);}
function audit(actorId,action,entityId,metadata,now=new Date().toISOString()){sql.prepare("INSERT INTO audit_logs (id,actor_id,action,entity_type,entity_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)").run(`audit_${randomUUID()}`,actorId,action,"report",entityId,metadata?JSON.stringify(metadata):null,now);}
function evidence(id){return sql.prepare("SELECT id,original_name AS originalName,mime_type AS mimeType,file_size AS fileSize,kind,uploaded_at AS uploadedAt FROM report_evidence WHERE report_id=? ORDER BY uploaded_at").all(id).map(e=>({...e,url:`/api/reports/${encodeURIComponent(id)}/evidence/${encodeURIComponent(e.id)}`}));}
function publicEvidence(id){return sql.prepare("SELECT id,original_name AS originalName,mime_type AS mimeType,uploaded_at AS uploadedAt FROM report_evidence WHERE report_id=? AND kind='citizen' ORDER BY uploaded_at").all(id).map(e=>({...e,url:`/api/reports/community/${encodeURIComponent(id)}/evidence/${encodeURIComponent(e.id)}`}));}
function communityCounts(reportId,userId){const totals=sql.prepare("SELECT SUM(vote_type='confirm') confirmed,SUM(vote_type='reject') rejected FROM community_votes WHERE report_id=?").get(reportId);const mine=userId?sql.prepare("SELECT vote_type FROM community_votes WHERE report_id=? AND user_id=?").get(reportId,userId):null;const confirmed=Number(totals?.confirmed||0),rejected=Number(totals?.rejected||0),total=confirmed+rejected,ratio=confirmed/Math.max(rejected,1),supported=total>=3&&ratio>=1.75,disputed=total>=3&&rejected>confirmed;return {confirmed,rejected,legit:confirmed,notLegit:rejected,totalVotes:total,verificationRatio:Math.round(ratio*100)/100,legitimacyPercent:total?Math.round((confirmed/total)*100):null,communityStatus:total<3?"awaiting_verification":supported?"community_supported":disputed?"community_disputed":"mixed",communitySupported:supported,communityPriorityBonus:supported?10:0,myVote:mine?.vote_type||null};}
function effectivePriority(row,counts=communityCounts(row.id)){return row.priority==null?null:Math.min(100,Number(row.priority)+Number(counts.communityPriorityBonus||0));}
function serializePublic(row,user){const counts=communityCounts(row.id,user?.id),images=publicEvidence(row.id),firstImage=images[0]||null,priority=effectivePriority(row,counts);return {id:row.id,title:row.title,description:row.description,category:row.category,categoryLabel:getCategory(row.category).label,status:row.status,priority,basePriority:row.priority,communityPriorityBonus:counts.communityPriorityBonus,severity:priority==null?"pending":priority>=85?"critical":priority>=70?"high":priority>=45?"medium":"low",department:row.department,reporterType:row.reporter_type||"registered",location:row.address,approximateLocation:row.address,createdAt:row.created_at,reportedAt:row.submitted_at,updatedAt:row.updated_at,imageUrl:firstImage?.url||null,evidence:images,...counts,canVote:user?.role==="citizen"&&row.citizen_id!==user.id&&isPublicReport(row)};}
function history(id){return sql.prepare("SELECT id,old_status AS oldStatus,new_status AS newStatus,changed_by AS changedBy,reason,created_at AS createdAt FROM report_status_history WHERE report_id=? ORDER BY created_at").all(id);}
function notes(id){return sql.prepare("SELECT n.id,n.content,n.created_at AS createdAt,u.name AS author FROM report_notes n LEFT JOIN users u ON u.id=n.author_id WHERE n.report_id=? ORDER BY n.created_at DESC").all(id);}
function serialize(row,{detail=false,staff=false,admin=false,publicOnly=false}={}){if(!row)return null;const counts=communityCounts(row.id),basePriority=row.priority,priority=effectivePriority(row,counts),severity=priority==null?"pending":priority>=85?"critical":priority>=70?"high":priority>=45?"medium":"low";const value={id:row.id,citizenId:staff&&row.reporter_type!==GUEST_REPORTER?row.citizen_id:undefined,reporterType:row.reporter_type||"registered",title:row.title,description:row.description,category:row.category,categoryLabel:getCategory(row.category).label,status:row.status,priority,basePriority,communityPriorityBonus:counts.communityPriorityBonus,communityStatus:counts.communityStatus,communitySupported:counts.communitySupported,severity,department:row.department,assignedAuthorityId:staff?row.assigned_authority_id:undefined,latitude:row.latitude,longitude:row.longitude,address:row.address,location:row.address,locationData:{latitude:row.latitude,longitude:row.longitude,name:row.address},ward:row.ward,municipality:row.municipality,province:row.province,statusReason:row.status_reason,resolutionNotes:row.resolution_notes,resolvedDetail:row.resolution_notes||row.resolved_at?{note:row.resolution_notes,resolvedAt:row.resolved_at,resolvedBy:row.resolved_by}:null,resolution:row.resolution_notes||row.resolved_at?{note:row.resolution_notes,resolvedAt:row.resolved_at,resolvedBy:row.resolved_by}:null,aiStatus:row.ai_status,aiCategory:row.ai_category,aiPriority:row.ai_priority,aiConfidence:row.ai_confidence,aiSummary:row.ai_summary||(row.ai_status==="failed"?"Automated analysis is temporarily unavailable; staff review is required.":"Automated analysis is pending."),aiDepartment:row.ai_department,aiAnalyzedAt:row.ai_analyzed_at,possibleDuplicateId:row.possible_duplicate_id,duplicateSimilarity:row.duplicate_similarity,createdAt:row.created_at,updatedAt:row.updated_at,reportedAt:row.submitted_at,submittedAt:row.submitted_at,acknowledgedAt:row.acknowledged_at,assignedAt:row.assigned_at,resolvedAt:row.resolved_at,resolvedBy:row.resolved_by,closedAt:row.closed_at};if(admin){const reporter=row.reporter_type===GUEST_REPORTER?null:sql.prepare("SELECT name,email,phone FROM users WHERE id=?").get(row.citizen_id);value.reporter=reporter?{name:reporter.name,email:reporter.email,phone:reporter.phone||""}:{name:"Anonymous",email:null,phone:null};}if(detail){const ev=publicOnly?[]:evidence(row.id);Object.assign(value,{evidence:ev,media:{photos:ev.filter(e=>e.kind==="citizen").length,voiceSec:null},timeline:history(row.id),activity:history(row.id).map(h=>({key:h.newStatus,at:h.createdAt,text:h.reason||`Status changed to ${h.newStatus}.`})),notes:staff?notes(row.id):undefined});}return value;}
function guestEvidence(id,token){return sql.prepare("SELECT id,original_name AS originalName,mime_type AS mimeType,kind,uploaded_at AS uploadedAt FROM report_evidence WHERE report_id=? AND kind IN ('citizen','resolution') ORDER BY uploaded_at").all(id).map(e=>({...e,url:`/api/guest/reports/${encodeURIComponent(id)}/evidence/${encodeURIComponent(e.id)}?token=${encodeURIComponent(token)}`}));}
function serializeGuest(row,token){const value=serialize(row,{detail:false,staff:false});const ev=guestEvidence(row.id,token);return {...value,evidence:ev,timeline:history(row.id),activity:history(row.id).map(h=>({key:h.newStatus,at:h.createdAt,text:h.reason||`Status changed to ${h.newStatus}.`}))};}
function validCoordinate(latitude,longitude){return Number.isFinite(Number(latitude))&&Number(latitude)>=-90&&Number(latitude)<=90&&Number.isFinite(Number(longitude))&&Number(longitude)>=-180&&Number(longitude)<=180&&!(Number(latitude)===0&&Number(longitude)===0);}
function mapVisibility(req){if(!req.user)return {clause:"status NOT IN ('rejected')",args:[]};if(req.user.role==="admin")return {clause:"",args:[]};if(req.user.role==="authority")return {clause:"(department=? OR assigned_authority_id=?)",args:[req.user.department,req.user.id]};return {clause:"citizen_id=?",args:[req.user.id]};}
function findDuplicate(input){const recent=sql.prepare("SELECT id,description,latitude,longitude FROM reports WHERE category=? AND created_at>=? ORDER BY created_at DESC LIMIT 50").all(input.category,new Date(Date.now()-30*86400000).toISOString());let best=null;const words=new Set(input.description.toLowerCase().split(/\W+/).filter(w=>w.length>3));for(const r of recent){const km=Math.hypot((r.latitude-input.latitude)*111,(r.longitude-input.longitude)*100);if(km>1)continue;const other=new Set(r.description.toLowerCase().split(/\W+/).filter(w=>w.length>3));const overlap=[...words].filter(w=>other.has(w)).length/Math.max(1,new Set([...words,...other]).size);const score=Math.round((Math.max(0,1-km)*.55+overlap*.45)*100);if(score>=55&&(!best||score>best.score))best={id:r.id,score};}return best;}
export async function runAI(id){const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(id);if(!row)return {ok:false,code:"NOT_FOUND"};try{const ev=sql.prepare("SELECT storage_name,mime_type,file_size FROM report_evidence WHERE report_id=? AND kind='citizen'").all(id);const ai=await analyzeReportWithAI({report:row,evidence:ev,uploadDir});sql.prepare("UPDATE reports SET ai_status='complete',ai_category=?,ai_priority=?,priority=?,ai_confidence=?,ai_summary=?,ai_department=?,ai_analyzed_at=?,updated_at=? WHERE id=?").run(ai.category,ai.priorityScore,ai.priorityScore,ai.confidence,ai.summary,ai.department,new Date().toISOString(),new Date().toISOString(),id);if(row.reporter_type!==GUEST_REPORTER)addNotification(row.citizen_id,id,"analysis","AI analysis completed",`CivicAI analysis is available for ${id}.`);return {ok:true,provider:ai.provider};}catch(error){sql.prepare("UPDATE reports SET ai_status='failed',updated_at=? WHERE id=?").run(new Date().toISOString(),id);console.error(JSON.stringify({event:"report_ai_failed",reportId:id,message:error.message}));return {ok:false,error};}}

export function resumePendingAnalyses(){
  const retryFailed=process.env.AI_RETRY_FAILED_ON_STARTUP !== "false";
  const statuses=retryFailed ? "('pending','failed')" : "('pending')";
  const rows=sql.prepare(`SELECT id FROM reports WHERE ai_status IN ${statuses} ORDER BY created_at LIMIT 100`).all();
  for(const row of rows){
    sql.prepare("UPDATE reports SET ai_status='pending',updated_at=? WHERE id=?").run(new Date().toISOString(),row.id);
    setImmediate(()=>runAI(row.id));
  }
}

function guestAccess(reportId, token) {
  if (typeof token !== "string" || token.length < 32) return null;
  const access = sql.prepare("SELECT * FROM guest_report_access WHERE report_id=? AND token_hash=?").get(reportId, hashGuestToken(token));
  if (!access || Date.now() >= access.expires_at) return null;
  return access;
}

reportsRouter.post("/guest/reports",guestCreateLimiter,upload.array("evidence",6),async(req,res,next)=>{let files=[];try{const parsed=validateReportInput(req.body||{});if(parsed.error)return fail(res,400,"VALIDATION_ERROR",parsed.error);files=await validateEvidence(req.files);const input=parsed.value;const id=reportId();const accessToken=guestToken();const now=new Date().toISOString();const expiresAt=Date.now()+GUEST_ACCESS_TTL_MS;const category=getCategory(input.category);sql.exec("BEGIN IMMEDIATE");try{sql.prepare("INSERT INTO reports (id,citizen_id,title,description,category,status,priority,department,assigned_authority_id,latitude,longitude,address,ward,municipality,province,status_reason,resolution_notes,ai_status,possible_duplicate_id,duplicate_similarity,reporter_type,community_priority_bonus,created_at,updated_at,submitted_at) VALUES (?,?,?,?,?,'submitted',NULL,?,NULL,?,?,?,?,?,?,NULL,NULL,'pending',?,?,'guest',0,?,?,?)").run(id,GUEST_REPORTER,input.title,input.description,input.category,category.department,input.latitude,input.longitude,input.address,input.ward,input.municipality,input.province,null,null,now,now,now);sql.prepare("INSERT INTO guest_report_access (id,report_id,token_hash,created_at,expires_at) VALUES (?,?,?,?,?)").run(`guest_access_${randomUUID()}`,id,hashGuestToken(accessToken),Date.now(),expiresAt);const ev=sql.prepare("INSERT INTO report_evidence (id,report_id,storage_name,original_name,mime_type,file_size,kind,uploaded_at) VALUES (?,?,?,?,?,?, 'citizen',?)");for(const f of files)ev.run(`ev_${randomUUID()}`,id,f.storageName,f.originalName,f.mimeType,f.size,now);sql.prepare("INSERT INTO report_status_history (id,report_id,old_status,new_status,changed_by,reason,created_at) VALUES (?,?,NULL,'submitted',?,?,?)").run(`hist_${randomUUID()}`,id,GUEST_REPORTER,"Anonymous guest report submitted.",now);sql.exec("COMMIT");}catch(error){sql.exec("ROLLBACK");throw error;}try{storeEvidence(files);}catch(error){sql.prepare("DELETE FROM reports WHERE id=?").run(id);removeEvidence(files);throw error;}console.info(JSON.stringify({event:"guest_report_created",reportId:id,evidenceCount:files.length}));setImmediate(()=>runAI(id));return ok(res,{...serializeGuest(sql.prepare("SELECT * FROM reports WHERE id=?").get(id),accessToken),trackingId:id,accessToken},201);}catch(error){removeEvidence(files);next(error);}});

reportsRouter.post("/guest/track",guestTrackLimiter,(req,res)=>{const trackingId=String(req.body?.trackingId||"").trim();const token=String(req.body?.accessToken||"").trim();const access=guestAccess(trackingId,token);if(!access)return fail(res,404,"NOT_FOUND","We couldn't find that guest complaint or its access token.");const row=sql.prepare("SELECT * FROM reports WHERE id=? AND reporter_type=?").get(trackingId,GUEST_REPORTER);if(!row)return fail(res,404,"NOT_FOUND","We couldn't find that guest complaint.");ok(res,serializeGuest(row,token));});

reportsRouter.get("/guest/reports/:id/evidence/:evidenceId",guestTrackLimiter,(req,res)=>{const token=String(req.query?.token||"");if(!guestAccess(req.params.id,token))return fail(res,404,"NOT_FOUND","Evidence not found.");const item=sql.prepare("SELECT * FROM report_evidence WHERE id=? AND report_id=? AND kind IN ('citizen','resolution')").get(req.params.evidenceId,req.params.id);if(!item)return fail(res,404,"NOT_FOUND","Evidence not found.");res.type(item.mime_type).set("Content-Disposition",`inline; filename*=UTF-8''${encodeURIComponent(item.original_name)}`).sendFile(path.join(uploadDir,item.storage_name));});

// Lightweight, role-scoped map records. Full report details remain behind /reports/:id.
reportsRouter.get("/reports/map",(req,res)=>{
  const visibility=mapVisibility(req);
  const allowedStatuses=new Set(["submitted","under_review","verified","assigned","in_progress","resolved","closed","rejected","reopened"]);
  const category=req.query.category?String(req.query.category):"",status=req.query.status?String(req.query.status):"",department=req.query.department?String(req.query.department).slice(0,100):"";
  if(status&&!allowedStatuses.has(status))return fail(res,400,"INVALID_FILTER","Invalid map status filter.");
  const where=["latitude IS NOT NULL","longitude IS NOT NULL","typeof(latitude) IN ('integer','real')","typeof(longitude) IN ('integer','real')","latitude BETWEEN -90 AND 90","longitude BETWEEN -180 AND 180","NOT (latitude=0 AND longitude=0)"];
  const args=[];
  if(visibility.clause){where.push(visibility.clause);args.push(...visibility.args);}
  if(category){where.push("category=?");args.push(category);}
  if(status){where.push("status=?");args.push(status);}
  if(department){where.push("department=?");args.push(department);}
  const rows=sql.prepare(`SELECT id,title,description,category,priority,status,department,latitude,longitude,address,submitted_at,updated_at FROM reports WHERE ${where.join(" AND ")} ORDER BY updated_at DESC LIMIT 1000`).all(...args);
  res.json({success:true,data:rows.filter(row=>validCoordinate(row.latitude,row.longitude)).map(row=>({id:row.id,title:row.title,description:String(row.description||"").slice(0,240),category:row.category,priority:row.priority,status:row.status,department:row.department,latitude:Number(row.latitude),longitude:Number(row.longitude),address:row.address,reportedAt:row.submitted_at,updatedAt:row.updated_at}))});
});

reportsRouter.post("/reports/analyze",requireAuth,async(req,res)=>{
  if(req.user.role!=="citizen")return fail(res,403,"CITIZEN_REQUIRED","Citizen account required.");
  const description=String(req.body?.description||"").trim();
  if(description.length<10)return fail(res,400,"VALIDATION_ERROR","Add a little more detail before running AI analysis.");
  try {
    const result=await analyzeReportWithAI({report:{title:String(req.body?.title||"Civic issue"),description,category:String(req.body?.category||"other"),address:String(req.body?.address||"")},evidence:[],uploadDir});
    return ok(res,{category:result.category,department:result.department,priority:result.priorityScore,confidence:result.confidence,summary:result.summary});
  } catch(error) {
    console.error(JSON.stringify({event:"draft_ai_failed",userId:req.user.id,message:error.message}));
    return fail(res,503,"AI_UNAVAILABLE","AI analysis is temporarily unavailable. You can still choose a category manually.");
  }
});

reportsRouter.post("/guest/analyze",guestCreateLimiter,async(req,res)=>{const description=String(req.body?.description||"").trim();if(description.length<10)return fail(res,400,"VALIDATION_ERROR","Add a little more detail before running AI analysis.");try{const result=await analyzeReportWithAI({report:{title:String(req.body?.title||"Civic issue"),description,category:String(req.body?.category||"other"),address:String(req.body?.address||"")},evidence:[],uploadDir});return ok(res,{category:result.category,department:result.department,priority:result.priorityScore,confidence:result.confidence,summary:result.summary});}catch(error){console.error(JSON.stringify({event:"guest_draft_ai_failed",message:error.message}));return fail(res,503,"AI_UNAVAILABLE","AI analysis is temporarily unavailable. You can still choose a category manually.");}});

reportsRouter.post("/reports",requireAuth,createLimiter,upload.array("evidence",6),async(req,res,next)=>{let files=[];try{if(req.user.role!=="citizen")return fail(res,403,"CITIZEN_REQUIRED","Only citizen accounts can submit reports.");const parsed=validateReportInput(req.body||{});if(parsed.error)return fail(res,400,"VALIDATION_ERROR",parsed.error);files=await validateEvidence(req.files);const input=parsed.value;const duplicate=findDuplicate(input);const id=reportId();const now=new Date().toISOString();const category=getCategory(input.category);sql.exec("BEGIN IMMEDIATE");try{sql.prepare("INSERT INTO reports (id,citizen_id,title,description,category,status,priority,department,assigned_authority_id,latitude,longitude,address,ward,municipality,province,status_reason,resolution_notes,ai_status,possible_duplicate_id,duplicate_similarity,created_at,updated_at,submitted_at) VALUES (?,?,?,?,?,'submitted',NULL,?,NULL,?,?,?,?,?,?,NULL,NULL,'pending',?,?,?, ?,?)").run(id,req.user.id,input.title,input.description,input.category,category.department,input.latitude,input.longitude,input.address,input.ward,input.municipality,input.province,duplicate?.id||null,duplicate?.score||null,now,now,now);const ev=sql.prepare("INSERT INTO report_evidence (id,report_id,storage_name,original_name,mime_type,file_size,kind,uploaded_at) VALUES (?,?,?,?,?,?, 'citizen',?)");for(const f of files)ev.run(`ev_${randomUUID()}`,id,f.storageName,f.originalName,f.mimeType,f.size,now);sql.prepare("INSERT INTO report_status_history (id,report_id,old_status,new_status,changed_by,reason,created_at) VALUES (?,?,NULL,'submitted',?,?,?)").run(`hist_${randomUUID()}`,id,req.user.id,"Report submitted by citizen.",now);addNotification(req.user.id,id,"submitted","Your report has been submitted",`${id} was received successfully.`,now);sql.exec("COMMIT");}catch(error){sql.exec("ROLLBACK");throw error;}try{storeEvidence(files);}catch(error){sql.prepare("DELETE FROM reports WHERE id=?").run(id);removeEvidence(files);throw error;}console.info(JSON.stringify({event:"report_created",reportId:id,userId:req.user.id,evidenceCount:files.length}));setImmediate(()=>runAI(id));return ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(id),{detail:true}),201);}catch(error){removeEvidence(files);next(error);}});

// One authoritative, role-scoped payload for the operations dashboard. The
// server derives the department from the authenticated session; clients never
// choose the scope of this query.
reportsRouter.get("/authority/dashboard",requireAuth,(req,res)=>{
  if (!["authority","admin"].includes(req.user.role)) return fail(res,403,"AUTHORITY_REQUIRED","Authority access required.");
  const where=[], args=[];
  if (req.user.role === "authority") { where.push("(department=? OR assigned_authority_id=?)"); args.push(req.user.department, req.user.id); }
  const clause=where.length?` WHERE ${where.join(" AND ")}`:"";
  const effectivePrioritySql="COALESCE(priority, 0) + COALESCE(community_priority_bonus, 0)";
  const rows=sql.prepare(`SELECT * FROM reports${clause} ORDER BY CASE WHEN priority IS NULL THEN 1 ELSE 0 END, ${effectivePrioritySql} DESC, updated_at DESC`).all(...args);
  const stats=sql.prepare(`SELECT COUNT(*) assigned, SUM(${effectivePrioritySql}>=80) highPriority, SUM(${effectivePrioritySql}>=85 AND status NOT IN ('resolved','closed')) critical, SUM(status='in_progress') inProgress, SUM(status IN ('resolved','closed')) completed, SUM(status IN ('submitted','under_review','verified','assigned')) pendingReview FROM reports${clause}`).get(...args);
  ok(res,{department:req.user.department||null,stats:Object.fromEntries(Object.entries(stats).map(([key,value])=>[key,Number(value||0)])),tasks:rows.map((row)=>serialize(row,{staff:true}))});
});

reportsRouter.get("/categories",requireAuth,(req,res)=>{
  if(req.user.role!=="admin")return fail(res,403,"ADMIN_REQUIRED","Administrator access required.");
  const rows=sql.prepare("SELECT category,COUNT(*) reportCount FROM reports GROUP BY category").all();
  const counts=new Map(rows.map((row)=>[row.category,Number(row.reportCount||0)]));
  ok(res,CATEGORIES.map((category)=>({...category,reportCount:counts.get(category.key)||0})));
});

reportsRouter.get("/reports",requireAuth,(req,res)=>{const page=Math.max(1,Number(req.query.page)||1);const limit=Math.min(100,Math.max(1,Number(req.query.limit)||20));const where=[];const args=[];if(req.user.role==="citizen"){where.push("citizen_id=?");args.push(req.user.id);}else if(req.user.role==="authority"){where.push("(department=? OR assigned_authority_id=?)");args.push(req.user.department,req.user.id);}if(req.query.status){where.push("status=?");args.push(String(req.query.status));}if(req.query.category){if(!CATEGORY_KEYS.has(String(req.query.category)))return fail(res,400,"INVALID_FILTER","Invalid category filter.");where.push("category=?");args.push(String(req.query.category));}if(req.query.department&&req.user.role==="admin"){where.push("department=?");args.push(String(req.query.department).slice(0,100));}if(req.query.search){where.push("(id LIKE ? OR title LIKE ? OR description LIKE ?)");const q=`%${String(req.query.search).slice(0,100)}%`;args.push(q,q,q);}const clause=where.length?` WHERE ${where.join(" AND ")}`:"";const total=sql.prepare(`SELECT COUNT(*) count FROM reports${clause}`).get(...args).count;const rows=sql.prepare(`SELECT * FROM reports${clause} ORDER BY created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,(page-1)*limit);ok(res,rows.map(r=>serialize(r,{staff:req.user.role!=="citizen",admin:req.user.role==="admin"})),200,{page,limit,total,pages:Math.ceil(total/limit)});});
reportsRouter.get("/reports/my",requireAuth,(req,res)=>{
  if(req.user.role!=="citizen")return fail(res,403,"CITIZEN_REQUIRED","Citizen account required.");
  const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Math.max(1,Number(req.query.limit)||20));
  const status=String(req.query.status||"all"),sort=String(req.query.sort||"newest"),search=String(req.query.search||"").trim().slice(0,100);
  const statuses=new Set(["all","submitted","under_review","verified","assigned","in_progress","resolved","closed"]);
  const orders={newest:"created_at DESC",oldest:"created_at ASC",priority:"priority IS NULL ASC, priority DESC, created_at DESC",updated:"updated_at DESC"};
  if(!statuses.has(status))return fail(res,400,"INVALID_FILTER","Invalid report status filter.");
  if(!orders[sort])return fail(res,400,"INVALID_SORT","Invalid report sort option.");
  const where=["citizen_id=?"],args=[req.user.id];
  if(status!=="all"){where.push("status=?");args.push(status);}
  if(search){where.push("(id LIKE ? OR title LIKE ? OR description LIKE ? OR category LIKE ? OR address LIKE ?)");const q=`%${search}%`;args.push(q,q,q,q,q);}
  const clause=` WHERE ${where.join(" AND ")}`;
  const filteredTotal=Number(sql.prepare(`SELECT COUNT(*) count FROM reports${clause}`).get(...args).count||0);
  const rows=sql.prepare(`SELECT * FROM reports${clause} ORDER BY ${orders[sort]} LIMIT ? OFFSET ?`).all(...args,limit,(page-1)*limit);
  const counts=sql.prepare("SELECT COUNT(*) total,SUM(status IN ('submitted','under_review','verified','assigned')) awaiting,SUM(status='in_progress') inProgress,SUM(status IN ('resolved','closed')) resolved,SUM(priority>=85) critical FROM reports WHERE citizen_id=?").get(req.user.id);
  const awaiting=Number(counts.awaiting||0);
  ok(res,{items:rows.map(r=>serialize(r)),stats:{total:Number(counts.total||0),awaiting,pending:awaiting,inProgress:Number(counts.inProgress||0),resolved:Number(counts.resolved||0),critical:Number(counts.critical||0)},pagination:{page,limit,total:filteredTotal,pages:Math.ceil(filteredTotal/limit),hasMore:page*limit<filteredTotal}});
});
function analyticsRange(value){const now=Date.now();const durations={"7d":7,"30d":30,"90d":90,"1y":365,all:36500};const days=durations[value]||30;return {days,start:now-days*86400000};}
function analyticsPriority(value){if(value==="critical")return "priority >= 85";if(value==="high")return "priority >= 70 AND priority < 85";if(value==="medium")return "priority >= 45 AND priority < 70";if(value==="low")return "priority >= 0 AND priority < 45";return "";}
function analyticsSeverity(value){return analyticsPriority(value);}
function analyticsLevel(score){const value=Number(score);if(!Number.isFinite(value))return "low";if(value>=85)return "critical";if(value>=70)return "high";if(value>=45)return "medium";return "low";}
function analyticsBucket(date,days){const d=new Date(date);if(Number.isNaN(d.getTime()))return null;if(days<=30)return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())).toISOString().slice(0,10);if(days<=90){const day=d.getUTCDay();d.setUTCDate(d.getUTCDate()-day);return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())).toISOString().slice(0,10);}return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`;}
function analyticsLabel(bucket,days){if(days>90){const [year,month]=bucket.split("-");return new Date(Date.UTC(Number(year),Number(month)-1,1)).toLocaleDateString("en-US",{month:"short",year:"numeric"});}return new Date(`${bucket}T00:00:00Z`).toLocaleDateString("en-US",{month:"short",day:"numeric"});}
reportsRouter.get("/reports-analytics",requireAuth,(req,res)=>{
  if(req.user.role!=="admin")return fail(res,403,"ADMIN_REQUIRED","Administrator access required.");
  const rangeValue=String(req.query.range||"30d");if(!["7d","30d","90d","1y","all"].includes(rangeValue))return fail(res,400,"INVALID_RANGE","Invalid analytics date range.");const {days,start}=analyticsRange(rangeValue);const where=["submitted_at >= ?"],args=[new Date(start).toISOString()];
  const category=String(req.query.category||""),severity=String(req.query.severity||""),priority=String(req.query.priority||""),status=String(req.query.status||""),department=String(req.query.department||""),ward=String(req.query.ward||"");
  const allowedStatuses=new Set(["submitted","under_review","verified","assigned","in_progress","resolved","closed","rejected","reopened"]);if(category&&!CATEGORIES.some((item)=>item.key===category))return fail(res,400,"INVALID_FILTER","Invalid category filter.");if(category){where.push("category=?");args.push(category);}if(severity){const expression=analyticsSeverity(severity);if(!expression)return fail(res,400,"INVALID_FILTER","Invalid severity filter.");where.push(expression);}if(priority){const expression=analyticsPriority(priority);if(!expression)return fail(res,400,"INVALID_FILTER","Invalid priority filter.");where.push(expression);}if(status&&!allowedStatuses.has(status))return fail(res,400,"INVALID_FILTER","Invalid status filter.");if(status){where.push("status=?");args.push(status);}if(department){where.push("department=?");args.push(department);}if(ward){where.push("ward=?");args.push(ward);}
  const rows=sql.prepare(`SELECT submitted_at,status,category,priority,department,ward,resolved_at FROM reports WHERE ${where.join(" AND ")}`).all(...args);
  const total=rows.length,resolved=rows.filter((row)=>["resolved","closed"].includes(row.status)).length,active=rows.filter((row)=>!["resolved","closed","rejected"].includes(row.status)).length,critical=rows.filter((row)=>Number(row.priority)>=85&&!["resolved","closed"].includes(row.status)).length,inProgress=rows.filter((row)=>row.status==="in_progress").length;
  const durations=rows.filter((row)=>row.resolved_at&&row.submitted_at).map((row)=>(new Date(row.resolved_at)-new Date(row.submitted_at))/86400000).filter(Number.isFinite);const avgResolutionDays=durations.length?Number((durations.reduce((sum,value)=>sum+value,0)/durations.length).toFixed(1)):0;
  const trendMap=new Map();for(const row of rows){const submittedBucket=analyticsBucket(row.submitted_at,days);if(submittedBucket){const item=trendMap.get(submittedBucket)||{submitted:0,resolved:0};item.submitted+=1;trendMap.set(submittedBucket,item);}if(row.resolved_at){const resolvedBucket=analyticsBucket(row.resolved_at,days);if(resolvedBucket){const item=trendMap.get(resolvedBucket)||{submitted:0,resolved:0};item.resolved+=1;trendMap.set(resolvedBucket,item);}}}
  const trend=[];const step=days<=30?86400000:days<=90?604800000:2592000000;for(let time=start;time<=Date.now();time+=step){const bucket=analyticsBucket(new Date(time),days),item=trendMap.get(bucket)||{submitted:0,resolved:0};trend.push({label:analyticsLabel(bucket,days),submitted:item.submitted,resolved:item.resolved});}
  const countBy=(key)=>{const counts=new Map();for(const row of rows)counts.set(row[key]||"Unspecified",(counts.get(row[key]||"Unspecified")||0)+1);return [...counts.entries()].sort((a,b)=>b[1]-a[1]).map(([value,count])=>({[key]:value,count}));};
  const byCategory=countBy("category");const bySeverity=["critical","high","medium","low"].map((level)=>({severity:level,count:rows.filter((row)=>analyticsLevel(row.priority)===level).length}));const priorityDistribution=bySeverity.map((item)=>({level:item.severity,count:item.count}));
  const hotspotMap=new Map();for(const row of rows){const key=row.ward||"Unspecified";const item=hotspotMap.get(key)||{count:0,priorities:[],categories:{}};item.count+=1;if(row.priority!=null)item.priorities.push(Number(row.priority));item.categories[row.category]=(item.categories[row.category]||0)+1;hotspotMap.set(key,item);}const hotspots=[...hotspotMap.entries()].sort((a,b)=>b[1].count-a[1].count).slice(0,10).map(([ward,item])=>{const max=Math.max(...item.priorities,0);const topCategory=Object.entries(item.categories).sort((a,b)=>b[1]-a[1])[0];return {ward,count:item.count,levelKey:analyticsLevel(max),topCategory:topCategory?.[0]||null};});
  const departmentMap=new Map();for(const row of rows){const key=row.department||"Unspecified";const item=departmentMap.get(key)||{total:0,resolved:0,durations:[]};item.total+=1;if(["resolved","closed"].includes(row.status)){item.resolved+=1;if(row.resolved_at&&row.submitted_at)item.durations.push((new Date(row.resolved_at)-new Date(row.submitted_at))/86400000);}departmentMap.set(key,item);}const departments=[...departmentMap.entries()].sort((a,b)=>b[1].total-a[1].total).map(([department,item])=>({department,active:item.total-item.resolved,resolved:item.resolved,avgResolutionDays:item.durations.length?Number((item.durations.reduce((sum,value)=>sum+value,0)/item.durations.length).toFixed(1)):0,resolutionRate:item.total?Math.round(item.resolved/item.total*100):0}));
  const insights=[];if(byCategory[0])insights.push({id:"category",icon:"category",title:`${byCategory[0].category} is the most reported issue`,body:`${byCategory[0].count} reports match the selected period and filters.`});if(critical)insights.push({id:"critical",icon:"critical",title:`${critical} critical issues need attention`,body:"Critical issues are based on the stored priority score and current status."});if(hotspots[0])insights.push({id:"hotspot",icon:"hotspot",title:`${hotspots[0].ward} is the busiest hotspot`,body:`${hotspots[0].count} reports are recorded in this ward.`});if(resolved)insights.push({id:"resolution",icon:"resolution",title:`${resolved} issues are resolved`,body:`The current resolution rate is ${total?Math.round(resolved/total*100):0}%.`});
  const filterOptions={categories:CATEGORIES.map((item)=>({value:item.key,label:item.label})),severities:["critical","high","medium","low"].map((value)=>({value,label:value[0].toUpperCase()+value.slice(1)})),priorities:["critical","high","medium","low"].map((value)=>({value,label:value[0].toUpperCase()+value.slice(1)})),statuses:["submitted","under_review","verified","assigned","in_progress","resolved","closed","rejected","reopened"].map((value)=>({value,label:value.replaceAll("_"," ").replace(/\b\w/g,(char)=>char.toUpperCase())})),departments:[...new Set([...CATEGORIES.map((item)=>item.department),...rows.map((row)=>row.department).filter(Boolean)])].map((value)=>({value,label:value})),wards:[...new Set(rows.map((row)=>row.ward).filter(Boolean))].sort().map((value)=>({value,label:value}))};
  const statuses=countBy("status");
  const community={confirmed:resolved,awaiting:active,reportedNotResolved:active,confirmationRate:total?Math.round(resolved/total*100):0};
  ok(res,{range:rangeValue,stats:{totalReports:total,activeIssues:active,criticalIssues:critical,inProgress,resolved,avgResolutionDays},total,trend,byCategory,categories:byCategory,bySeverity,priorityDistribution,hotspots,resolution:{resolved,active,resolutionRate:total?Math.round(resolved/total*100):0,avgResolutionDays},community,departments,statuses,insights,filterOptions,updatedAt:new Date().toISOString()});
});
reportsRouter.get("/reports/community",requireAuth,(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Math.max(1,Number(req.query.limit)||20));const where=["status IN ('submitted','under_review','verified','assigned','in_progress','resolved','closed')"],args=[];const search=String(req.query.search||"").trim().slice(0,100);if(search){where.push("(id LIKE ? OR title LIKE ? OR description LIKE ? OR category LIKE ? OR address LIKE ?)");const q=`%${search}%`;args.push(q,q,q,q,q);}const clause=` WHERE ${where.join(" AND ")}`;const total=Number(sql.prepare(`SELECT COUNT(*) count FROM reports${clause}`).get(...args).count||0);const rows=sql.prepare(`SELECT id,citizen_id,reporter_type,title,description,category,status,priority,department,address,created_at,updated_at,submitted_at FROM reports${clause} ORDER BY created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,(page-1)*limit);ok(res,{items:rows.map(row=>serializePublic(row,req.user)),pagination:{page,limit,total,pages:Math.ceil(total/limit),hasMore:page*limit<total}});});
reportsRouter.get("/reports/community/:id",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!isPublicReport(row))return fail(res,404,"NOT_FOUND","Community report not found.");ok(res,serializePublic(row,req.user));});
reportsRouter.get("/reports/community/:id/evidence/:evidenceId",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!isPublicReport(row))return fail(res,404,"NOT_FOUND","Evidence not found.");const item=sql.prepare("SELECT * FROM report_evidence WHERE id=? AND report_id=? AND kind='citizen'").get(req.params.evidenceId,row.id);if(!item)return fail(res,404,"NOT_FOUND","Evidence not found.");res.type(item.mime_type).set("Content-Disposition",`inline; filename*=UTF-8''${encodeURIComponent(item.original_name)}`).sendFile(path.join(uploadDir,item.storage_name));});
reportsRouter.get("/reports/:id",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");if(!canView(req.user,row)){console.warn(JSON.stringify({event:"report_access_denied",reportId:req.params.id,userId:req.user.id}));return fail(res,403,"FORBIDDEN","You do not have access to this report.");}ok(res,serialize(row,{detail:true,staff:req.user.role!=="citizen",admin:req.user.role==="admin",publicOnly:req.user.role==="citizen"&&row.citizen_id!==req.user.id}));});
reportsRouter.get("/reports/:id/evidence/:evidenceId",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||!canViewEvidence(req.user,row))return fail(res,404,"NOT_FOUND","Evidence not found.");const item=sql.prepare("SELECT * FROM report_evidence WHERE id=? AND report_id=?").get(req.params.evidenceId,row.id);if(!item)return fail(res,404,"NOT_FOUND","Evidence not found.");res.type(item.mime_type).set("Content-Disposition",`inline; filename*=UTF-8''${encodeURIComponent(item.original_name)}`).sendFile(path.join(uploadDir,item.storage_name));});
reportsRouter.get("/reports/:id/community",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||(!canView(req.user,row)&&!isPublicReport(row)))return fail(res,404,"NOT_FOUND","Report not found.");ok(res,{...communityCounts(row.id,req.user.id),canVote:req.user.role==="citizen"&&row.citizen_id!==req.user.id&&isPublicReport(row)});});
reportsRouter.post("/reports/:id/community",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||!isPublicReport(row))return fail(res,404,"NOT_FOUND","Community report not found.");if(req.user.role!=="citizen")return fail(res,403,"CITIZEN_REQUIRED","Only citizens can react to community reports.");if(row.citizen_id===req.user.id)return fail(res,403,"SELF_VOTE","You cannot verify your own report.");const vote=String(req.body?.vote||"");if(!["confirm","reject"].includes(vote))return fail(res,400,"VALIDATION_ERROR","Choose confirm or reject.");const now=new Date().toISOString();sql.prepare("INSERT INTO community_votes (id,report_id,user_id,vote_type,created_at,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(report_id,user_id) DO UPDATE SET vote_type=excluded.vote_type,updated_at=excluded.updated_at").run(`vote_${randomUUID()}`,row.id,req.user.id,vote,now,now);const counts=communityCounts(row.id,req.user.id);sql.prepare("UPDATE reports SET community_priority_bonus=?,updated_at=? WHERE id=?").run(counts.communityPriorityBonus,now,row.id);ok(res,counts);});
reportsRouter.post("/reports/:id/status",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");if(!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot update this report.");const next=String(req.body?.status||"");if(!STATUS_TRANSITIONS[row.status]?.includes(next))return fail(res,409,"INVALID_TRANSITION",`Cannot move this report from ${row.status} to ${next}.`);const reasonResult=req.body?.reason?cleanText(req.body.reason,{min:3,max:500,name:"Reason"}):{value:null};if(reasonResult.error)return fail(res,400,"VALIDATION_ERROR",reasonResult.error);const now=new Date().toISOString();sql.exec("BEGIN IMMEDIATE");try{sql.prepare("UPDATE reports SET status=?,status_reason=?,updated_at=?,acknowledged_at=CASE WHEN ?='under_review' THEN COALESCE(acknowledged_at,?) ELSE acknowledged_at END,assigned_at=CASE WHEN ?='assigned' THEN COALESCE(assigned_at,?) ELSE assigned_at END,resolved_at=CASE WHEN ?='resolved' THEN ? ELSE resolved_at END,resolved_by=CASE WHEN ?='resolved' THEN ? ELSE resolved_by END,closed_at=CASE WHEN ?='closed' THEN ? ELSE closed_at END WHERE id=?").run(next,reasonResult.value,now,next,now,next,now,next,now,next,req.user.id,next,now,row.id);sql.prepare("INSERT INTO report_status_history VALUES (?,?,?,?,?,?,?)").run(`hist_${randomUUID()}`,row.id,row.status,next,req.user.id,reasonResult.value,now);if(row.reporter_type!==GUEST_REPORTER)addNotification(row.citizen_id,row.id,"status",`Report status: ${next.replaceAll("_"," ")}`,reasonResult.value||`${row.id} is now ${next.replaceAll("_"," ")}.`,now);sql.exec("COMMIT");}catch(error){sql.exec("ROLLBACK");throw error;}console.info(JSON.stringify({event:"report_status_changed",reportId:row.id,from:row.status,to:next,actor:req.user.id}));ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(row.id),{detail:true,staff:true}));});
function removeReportForAdmin(req,res,id,action){const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");if(req.user.role!=="admin")return fail(res,403,"ADMIN_REQUIRED","Only administrators can remove reports.");const files=sql.prepare("SELECT storage_name AS storageName FROM report_evidence WHERE report_id=?").all(id);const now=new Date().toISOString();sql.exec("BEGIN IMMEDIATE");try{audit(req.user.id,action,id,{status:row.status,reporterType:row.reporter_type||"registered"},now);sql.prepare("DELETE FROM reports WHERE id=?").run(id);sql.exec("COMMIT");}catch(error){sql.exec("ROLLBACK");throw error;}removeEvidence(files);console.info(JSON.stringify({event:action.toLowerCase(),reportId:id,actor:req.user.id,status:row.status}));return ok(res,{id,removed:true,action},200);}
reportsRouter.delete("/reports/:id",requireAuth,(req,res)=>removeReportForAdmin(req,res,req.params.id,"REPORT_DELETED"));
reportsRouter.post("/reports/:id/reject",requireAuth,(req,res)=>removeReportForAdmin(req,res,req.params.id,"REPORT_REJECTED_AND_REMOVED"));
reportsRouter.post("/reports/:id/assign",requireAuth,(req,res)=>{if(req.user.role!=="admin")return fail(res,403,"ADMIN_REQUIRED","Only administrators can assign reports.");const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");const department=String(req.body?.department||"").trim().slice(0,100);if(!DEPARTMENTS.has(department))return fail(res,400,"INVALID_DEPARTMENT","Choose a valid CivicAI department.");const authority=req.body?.authorityId?sql.prepare("SELECT * FROM users WHERE id=? AND role='authority' AND status='active'").get(req.body.authorityId):null;if(req.body?.authorityId&&!authority)return fail(res,400,"VALIDATION_ERROR","Choose a valid active authority.");if(authority?.department&&authority.department!==department)return fail(res,400,"VALIDATION_ERROR","Authority does not belong to the selected department.");const now=new Date().toISOString();sql.exec("BEGIN IMMEDIATE");try{sql.prepare("UPDATE report_assignments SET unassigned_at=? WHERE report_id=? AND unassigned_at IS NULL").run(now,row.id);if(authority)sql.prepare("INSERT INTO report_assignments (id,report_id,authority_id,department,assigned_by,assigned_at) VALUES (?,?,?,?,?,?)").run(`asgn_${randomUUID()}`,row.id,authority.id,department,req.user.id,now);sql.prepare("UPDATE reports SET department=?,assigned_authority_id=?,updated_at=? WHERE id=?").run(department,authority?.id||null,now,row.id);audit(req.user.id,authority?"AUTHORITY_ASSIGNED":"DEPARTMENT_CHANGED",row.id,{department,authorityId:authority?.id||null},now);sql.exec("COMMIT");}catch(error){sql.exec("ROLLBACK");throw error;}ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(row.id),{detail:true,staff:true}));});
reportsRouter.post("/reports/:id/notes",requireAuth,(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot add notes to this report.");const note=cleanText(req.body?.content,{min:2,max:2000,name:"Note"});if(note.error)return fail(res,400,"VALIDATION_ERROR",note.error);const item={id:`note_${randomUUID()}`,createdAt:new Date().toISOString()};sql.prepare("INSERT INTO report_notes VALUES (?,?,?,?,?)").run(item.id,row.id,req.user.id,note.value,item.createdAt);ok(res,{...item,content:note.value,author:req.user.name},201);});
reportsRouter.post("/reports/:id/resolution",requireAuth,upload.single("evidence"),async(req,res,next)=>{let files=[];try{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row||!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot add resolution evidence.");files=await validateEvidence(req.file?[req.file]:[]);const note=req.body?.note?cleanText(req.body.note,{min:2,max:1000,name:"Resolution note"}):{value:null};if(note.error)return fail(res,400,"VALIDATION_ERROR",note.error);if(!files.length&&!note.value)return fail(res,400,"VALIDATION_ERROR","Add a resolution note or upload an evidence image.");const now=new Date().toISOString();let result={note:note.value,uploadedAt:now};if(files.length){storeEvidence(files);const f=files[0],id=`ev_${randomUUID()}`;try{sql.prepare("INSERT INTO report_evidence VALUES (?,?,?,?,?,?,'resolution',?)").run(id,row.id,f.storageName,f.originalName,f.mimeType,f.size,now);sql.prepare("UPDATE reports SET resolution_notes=COALESCE(?,resolution_notes),updated_at=? WHERE id=?").run(note.value,now,row.id);result={...result,id,url:`/api/reports/${row.id}/evidence/${id}`};}catch(error){removeEvidence(files);throw error;}}else{sql.prepare("UPDATE reports SET resolution_notes=COALESCE(?,resolution_notes),updated_at=? WHERE id=?").run(note.value,now,row.id);}ok(res,result,201);}catch(error){next(error);}});
reportsRouter.post("/reports/:id/ai/retry",requireAuth,async(req,res)=>{const row=sql.prepare("SELECT * FROM reports WHERE id=?").get(req.params.id);if(!row)return fail(res,404,"NOT_FOUND","Report not found.");if(!canManage(req.user,row))return fail(res,403,"FORBIDDEN","You cannot retry analysis.");sql.prepare("UPDATE reports SET ai_status='pending' WHERE id=?").run(row.id);const result=await runAI(row.id);if(!result.ok)return fail(res,503,"AI_UNAVAILABLE","AI analysis is temporarily unavailable. The report remains saved and can be retried.");ok(res,serialize(sql.prepare("SELECT * FROM reports WHERE id=?").get(row.id),{detail:true,staff:true}));});
reportsRouter.get("/notifications",requireAuth,(req,res)=>{const rows=sql.prepare("SELECT id,report_id AS reportId,kind,title,body,read_at AS readAt,created_at AS createdAt FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50").all(req.user.id);ok(res,{items:rows.map(n=>({...n,unread:!n.readAt}))});});
reportsRouter.post("/notifications/read",requireAuth,(req,res)=>{const ids=Array.isArray(req.body?.ids)?req.body.ids.map((id)=>String(id).slice(0,100)).filter(Boolean):[];const now=new Date().toISOString();if(req.body?.all===true){sql.prepare("UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL").run(now,req.user.id);}else if(ids.length){const placeholders=ids.map(()=>"?").join(",");sql.prepare(`UPDATE notifications SET read_at=? WHERE user_id=? AND id IN (${placeholders})`).run(now,req.user.id,...ids);}const unread=Number(sql.prepare("SELECT COUNT(*) count FROM notifications WHERE user_id=? AND read_at IS NULL").get(req.user.id).count||0);ok(res,{unread});});
